--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Eric-pm-pl/EnchantShopUI
branches:
- master
projects:
  EnchantShopUI:
    path: ""
    icon: "/logo.png"
    libs:
    - src: dktapps-pm-pl/pmforms/pmforms
      version: ^1.0.0
    lint:
      phpstan: false
...
