name: EnchantShopUI
main: YTBJero\EnchantShopUI\Main
version: 0.7
api: 4.0.0
load: POSTWORLD
author: 
  - YTBJero
  - UnknownOre
softdepend: [PiggyCustomEnchants, BedrockEconomyAPI]

permissions:
  eshop.command:
    default: true
    description: "use all EnchantShopUI Commands"
